import { DM_Sans, Lora, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const dmSans = DM_Sans({
  variable: "--font-sans", // Matches your global CSS variable
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Optional weights
});

const lora = Lora({
  variable: "--font-serif", // Matches your global CSS variable
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Optional weights
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-mono", // Matches your global CSS variable
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Optional weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${lora.variable} ${ibmPlexMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
